# Generated by Django 2.0 on 2018-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0002_auto_20180102_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogs',
            name='agent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loginlogs',
            name='ip_addres',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loginlogs',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loginlogs',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loginlogs',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
