# Generated by Django 2.0 on 2018-01-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0002_auto_20180102_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlogs',
            name='is_verified',
        ),
    ]
