# Generated by Django 2.0 on 2018-01-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0003_remove_loginlogs_is_verified'),
        ('log_in', '0003_auto_20180103_0708'),
    ]

    operations = [
    ]
