# Generated by Django 2.0 on 2018-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0003_remove_loginlogs_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password_reset_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
