# Generated by Django 2.0 on 2018-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0004_merge_20180103_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogs',
            name='otp_verified',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
