# Generated by Django 2.0 on 2018-01-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0005_loginlogs_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogs',
            name='agent',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
