# Generated by Django 2.0 on 2018-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0008_auto_20180103_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogs',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginlogs',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
