# Generated by Django 2.0 on 2018-01-03 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0009_auto_20180103_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogs',
            name='user_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
