# Generated by Django 2.0 on 2018-01-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0010_auto_20180103_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogs',
            name='logintry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
