# Generated by Django 2.0 on 2018-01-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0011_loginlogs_logintry_time'),
        ('log_in', '0004_myuser_password_reset_token'),
    ]

    operations = [
    ]
