# Generated by Django 2.0 on 2018-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0014_auto_20180104_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password_reset_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
