# Generated by Django 2.0 on 2018-01-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0016_sessionkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionkey',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='loginlogs',
            options={'get_latest_by': 'email'},
        ),
        migrations.DeleteModel(
            name='SessionKey',
        ),
    ]
