# Generated by Django 2.0 on 2018-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0017_auto_20180108_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockerno', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('foldername', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
