# Generated by Django 2.0 on 2018-06-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0018_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='filename',
        ),
    ]
